### ISSUE TITLE
Incorrect version guard in `CNIOOpenSSL_TLS_Method`?

### ISSUE THREAD

**Issue by tengyifei** [apple/swift-nio-ssl#48]
From https://www.openssl.org/docs/man1.1.0/ssl/TLS_method.html, "TLS_method(), TLS_server_method() and TLS_client_method() functions were introduced in OpenSSL 1.1.0."

But the version guard in https://github.com/apple/swift-nio-ssl/blob/master/Sources/CNIOOpenSSL/shims.c#L37 states `0x10100000L`.

This resulted in compiling against e.g. OpenSSL 1.0.1p to trigger an undefined symbol error for `TLS_method`.

**Comment by Lukasa** [comment]
That version guard is correct as far as I can see: do you have your full compiler output?

**Comment by tengyifei** [comment]
Perhaps I'm abusing SPM a bit :) The steps that led to the error were as follows:

1. Create a SPM project (let's name it `SPMPackage`) with a static-library target and depending on `swift-nio-ssl`.

2. Build the library in release mode, then import the swiftmodule and `SPMPackage.a` in an Xcode project and link against a Cocoa app. I also link it with OpenSSL 1.0.1p, which is the latest version on macOS homebrew.

3. Attempt to build the app, which fails at link time with the following error:

```
Undefined symbols for architecture x86_64:
  "_TLS_method", referenced from:
      _CNIOOpenSSL_TLS_Method in libSPMPackage.a(shims.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

4. Manually define a `TLS_method` C function which just calls `SSLv23_method`. Then it works as expected.

**Comment by Lukasa** [comment]
Your linking is not working properly. The header guard itself is fine, but it's present in the *header file*. If you compile with an OpenSSL 1.1 header file, but link against an OpenSSL < 1.1 library, you will see this error message.

In this case, you should investigate *exactly which openssl version* Xcode is linking your app against, because I think it's not the same OpenSSL version you built your static library against.

(Incidentally, OpenSSL 1.0.1p is not the latest version on macOS homebrew: I don't know where you got that idea. There are two formulae in Homebrew: `openssl` brings in [1.0.2p](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb#L7), and `openssl@1.1` brings in [OpenSSL 1.1.1](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb#L4).)

**Comment by tengyifei** [comment]
(Sorry I made a typo regarding OpenSSL 1.0.1p. It should really be OpenSSL 1.0.2p.)

Thank you for the quick response! You're right that the version guard is fine. I suspect that that SPM built the archive under a newer/different header.

On a side note, it would be really nice if SPM could be more explicit about system dependencies. Right now despite https://github.com/apple/swift-nio-ssl-support specifying OpenSSL in `pkgConfig`, in reality it uses LibreSSL on macOS under some undocumented logic around a `Brewfile`
