### ISSUE TITLE
swift-nio-ssl not working in a sandboxed app

### ISSUE THREAD

**Issue by fappelman** [apple/swift-nio-ssl#19]
Hi,

I am using swift-nio and it works perfectly. So far I worked on the command line and everything worked as expected. I then started using the created library from a Mac App with a GUI and and soon as I enable SSL I see the following in the logs:

```log
Auto configuration failed
4318397384:error:02FFF001:system library:func(4095):Operation not permitted:bio/bss_file.c:122:fopen('/usr/local/etc/libressl/openssl.cnf', 'rb')
4318397384:error:20FFF002:BIO routines:CRYPTO_internal:system lib:bio/bss_file.c:127:
4318397384:error:0EFFF002:configuration file routines:CRYPTO_internal:system lib:conf/conf_def.c:200:
```

I can make it work by removing the sandboxing of the app but that is not really a solution given that sandboxing is the way forward.

Do you have any advise on how to approach this? 

Thanks.

**Comment by Lukasa** [comment]
Unfortunately, I believe that App Sandbox is not compatible with libressl's default configuration behaviour as supported by swift-nio-ssl. As far as I know it is not possible to request an entitlement to `/usr/local`, nor can we use the open file dialog here, as this behaviour is controlled by libssl.

In principle we could add an override to allow opening a config file from an arbitrary location instead of from the default location on the system, which would allow you to ship a config file inside your sandbox instead of from elsewhere. This is moderately tricky to hold correctly though, as you would need to guarantee that you did that *first*, before using any of `swift-nio-ssl`, but it's in principle do-able.

If you don't mind my asking, what is your minimum deployment platform for this application?

**Comment by fappelman** [comment]
Thanks for the quick response. At this moment I have not really defined a minimum deployment platform. If that helps I'm happy to limit it to the latest. 

Just asking, <https://developer.apple.com/documentation/security/secure_transport> seems to be the standard. Is there a reason why this was no used?

**Comment by helje5** [comment]
Does Network.framework support server sockets? I'm also very much interested in this thing (TLS server sockets in AppStore apps).

**Comment by Lukasa** [comment]
@helje5 Sure does. 👍

**Comment by fappelman** [comment]
Sounds good to me. Looking forward to the Network framework support.

**Comment by Lukasa** [comment]
iOS 12+, macOS 10.14+, tvOS 12+.

**Comment by helje5** [comment]
So at least I would need a different, temporary solution until about 2020 I guess (don’t get me wrong, supporting Network.fw sounds cool to me).
If I get to the point, I can have a look myself, but I think it would be good to keep the issue open and provide something that works on older setups.

**Comment by Lukasa** [comment]
Agreed, I see no reason to close this issue. I will reframe it as "use custom openssl/libressl configuration file location" though, which is the fix we'd need to make to resolve this problem.

For anyone who feels like picking this up, we probably need to make [this function](https://github.com/apple/swift-nio-ssl/blob/0adc938bc8de3d3829b842f9767d81c7480b8403/Sources/NIOOpenSSL/SSLInit.swift#L26) public, and extend it to take an optional `String` that we pass [here](https://github.com/apple/swift-nio-ssl/blob/0adc938bc8de3d3829b842f9767d81c7480b8403/Sources/NIOOpenSSL/SSLInit.swift#L32). We'll also need to update the logic for [this](https://github.com/apple/swift-nio-ssl/blob/0adc938bc8de3d3829b842f9767d81c7480b8403/Sources/NIOOpenSSL/SSLContext.swift#L21), but that'd probably do-able.

**Comment by segabor** [comment]
What's the exact version of openssl / libressl which is required to build NIO SSL? I'm having really hard time to build NIO based projects on Arch Linux as
- openssl 1.1 is the current supported library although NIO does not compile with it.
- openssl 1.0 can be installed but it is installed elsewhere not to conflict with 1.1. Some Swift packages can be built with extra -Xswiftc and -Xlinker parameters but others not.
- libressl is not recommended on Arch Linux as a successful install might ruin the whole system.
So the situation is quite disappointing.
Just came this idea into my mind: what if project embeds libressl portable making NIO fully independent of the current SSL implementations at OS / userland level?

**Comment by Lukasa** [comment]
> openssl 1.1 is the current supported library although NIO does not compile with it.

What do you mean? It should compile fine. What errors are you encountering?

> Just came this idea into my mind: what if project embeds libressl portable making NIO fully independent of the current SSL implementations at OS / userland level?

This cannot be done today. The primary reason why is that [swift-corelibs-foundation](https://github.com/apple/swift-corelibs-foundation) links libcurl to provide an implementation for `URLSession`, and libcurl links the system OpenSSL. As Linux has a single symbol table, if we separately statically link the same symbols (via libressl portable, or via boringssl statically linked) into our main binary, we will cause a symbol clash and cause horrifying breakages (see #16).

**Comment by segabor** [comment]
@Lukasa I was wrong, indeed it compiles but one test fails. I thought it was NIO that broke Vapor app builds.

The only failing test is below,
```
/home/segabor/Workspace/swift-nio/Tests/NIOTests/IntegerTypesTest.swift:88:44: error: integer literal '12345678' overflows when stored into '_UInt24.IntegerLiteralType' (aka 'UInt16')
        XCTAssertEqual("12345678", _UInt24(12345678).description)
                                           ^
```
Swift version 4.2-dev (LLVM c4295e5d5d, Clang afaa327551, Swift 7ae5a7af6a)
Target: x86_64-unknown-linux-gnu

**Comment by Lukasa** [comment]
That seems like a Swift compiler bug to me. Where did your swift compiler come from?

The issue is that the compiler is attempting to use the `_UInt24(integerLiteral:)` constructor to turn `12345678` into a `_UInt24` directly. There is no reason it should do that, as `_UInt24` has no constructor that accepts a `_UInt24` anyway, which means that the wrapping call would not work.

**Comment by segabor** [comment]
Well I built it manually as Swift support on Arch Linux is quite sporadic (4.1.3 is the last working build, 4.2 release does not build yet) and I really wanted to use 4.2.

**Comment by Lukasa** [comment]
Interesting, this seems new. You're building your Swift off a newer commit than the 4.2 release: if you have the spare CPU cycles do you want to try using the 4.2 release tag as HEAD for the swift build? That may well resolve your issue, as the nightlies do have a tendency to introduce transient regressions of this type.

**Comment by Lukasa** [comment]
(I'll also investigate this with the nightlies when I have a few spare moments later today.)

**Comment by Lukasa** [comment]
This appears to still fail on master: @lorentey has kindly filed a swift bug as [SR-8816](https://bugs.swift.org/browse/SR-8816).

**Comment by segabor** [comment]
Another thing. I got back to stable(?) 4.1.3 and rebuilt Vapor test application now I'm having the following error:
```
/home/segabor/Workspace/VaporTestApp/.build/checkouts/swift-nio-ssl.git--3265017750353408729/Sources/NIOOpenSSL/SSLContext.swift:311:90: error: member 'init' in 'UnsafeMutableRawPointer!' produces result of type 'ImplicitlyUnwrappedOptional<Wrapped>', but context expects 'UnsafeMutableRawPointer!'
        guard 1 == SSL_CTX_ctrl(.make(optional: context), SSL_CTRL_EXTRA_CHAIN_CERT, 0, .init(X509_dup(.make(optional: cert.ref)))) else {
```

I suppose 4.1.3 should be fine with Vapor 3 and latest NIO.

**Comment by segabor** [comment]
I replaced AUR package 'swift-language' with 'swift-bin' that's essentially official Ubuntu package. I got the same error. Provided it should build with 4.1.3 I'm going to open a new issue for this.

**Comment by Lukasa** [comment]
I cannot reproduce this issue with Swift 4.1.3 from the swift.org toolchain: swift-nio-ssl builds and tests just fine for me.

**Comment by segabor** [comment]
No idea, what's going on. Both Swift 4.1 (!!) and 4.2-dev produces the same error. Now I think there must be definitely broken underneath (most probably C to Swift conversion fails due to header issue).
Now I stop flooding this ticket. Once I get the whole mess done I let you know.
Many thanks for your patience.

**Comment by segabor** [comment]
@Lukasa happy to to report that Swift 4.2 finally arrived to Arch Linux resolving all the mysterious issues came with the custom Swift binary. Not to mention that Vapor also got an update. All my pain relieved :)

**Comment by Lukasa** [comment]
@segabor Glad to hear it! :tada:

**Comment by weissi** [comment]
@Lukasa does this need re-eval now that we have the new shiny vendored BoringSSL thing?

**Comment by Lukasa** [comment]
Yes. Let’s investigate this week.

**Comment by weissi** [comment]
@Lukasa / @segabor / @fappelman this should be fixed with NIO2 I believe.

**Comment by fappelman** [comment]
I have used NIO2 successfully.

**Comment by weissi** [comment]
Thank you, considering this fixed then. Please reopen if that’s still an issue.
